---
title: "Customers dashboard"
format:
  dashboard:
      nav-buttons:
        - icon: globe
          href: https://www.cleandata.sk/
          aria-label: www.cleandata.sk
        - icon: github
          href: https://github.com/Arnold-Kakas/Quarto-Customers-Dashboard
      logo: data/static/cleandata_logo.png
      include-in-header:
        text: |
          <link rel="icon" type="image/x-icon" href="data/static/dashboard.ico">
          <link href='https://fonts.googleapis.com/css?family=Maven Pro' rel='stylesheet'>
      theme:
        - flatly
        - custom.scss
---

```{r, init-load}
#| label: load-packages
#| echo: false
#| eval: true
#| warning: false
#| output: false

source("R/init load.R")
```

#

## Filters {.sidebar}

```{r, filter-reps}
filter_checkbox("specialist_filter", "Sales rep.", sd_customers, ~specialist)
```

```{r, filter-type}
filter_checkbox("customer_type_filter", "Customer type", sd_customers, ~customer_type)
```

## Body column

### KPI row {height="15%"}

```{r, valuebox-rate}
#| content: valuebox
#| title: "Conversion rate"
#| icon: check2-square
#| color: "#a6d5e0"
#| expandable: false

htmltools::browsable(kpiwidget(
  sd_customers,
  kpi = "count",
  comparison = "share",
  group1 = ~ customer_type %in% c("interný", "akvírovaný"),
  digits = 1,
  suffix = "%"
))
```

```{r, valuebox-count}
#| content: valuebox
#| title: "New Customers"
#| icon: person-plus-fill
#| color: "#a6d5e0"
#| expandable: false

htmltools::browsable(kpiwidget(
  sd_customers,
  statistic = "distinctCount",
  selection = ~ first_order_date >= twelve_months_ago
))
```

```{r, valuebox-sum}
#| content: valuebox
#| title: "Sales Amount"
#| icon: cash
#| color: "#a6d5e0"
#| expandable: false

htmltools::browsable(kpiwidget(
  sd_customers,
  statistic = "sum",
  column = "sales_amount",
  suffix = " €"
))
```
### Body row {height="85%"}

#### Map {width="50%"}

```{r, map}
#| title: "Geographical distribution of customers"
# Leaflet map with crosstalk

leaflet(sd_customers) |>
  addTiles() |>
  # addProviderTiles("Stadia.AlidadeSmooth") |>
  addPolygons(
    data = slovak_districts,
    fillColor = ~ pal_specialist(specialist),
    color = "black",
    weight = 0.5,
    opacity = 0.1,
    fillOpacity = 0.4,
    label = ~label
  ) |>
  addLegend(
    "bottomright",
    colors = c("#D3AF37", "#3D729E", "#C4A484"),
    labels = c("Interný", "akvírovaný", "prospekt"),
    title = "Customer Type",
    opacity = 1
  ) |>
  setView(lng = mean(slovak_districts$long), lat = mean(slovak_districts$lat), zoom = 7) |>
  addCircles(
    data = sd_customers,
    lng = ~lng,
    lat = ~lat,
    color = ~marker_color,
    label = ~label,
    opacity = 1,
    radius = 20,
    weight = 10
    # group = "customers"
  )
```


#### Table {width="50%"}
```{r, table}
#| title: "List of Customers"
#| expandable: false

datatable(
  sd_customers,
  extensions = c("Buttons", "FixedColumns"),
  rownames = FALSE,
  filter = "top",
  options = list(
    initComplete = JS(
      "function(settings, json) {",
      "$('body').css({'font-size': '12px', 'font-family': 'Arial'});",
      "}"
    ),
    columnDefs = list(list(
      visible = FALSE,
      targets = c(6:9)
    )),
    pageLength = 20,
    scrollY = "500px",
    dom = "Blrtp",
    deferRender = TRUE,
    buttons = c("excel", "csv"),
    autoWidth = FALSE
  ),
  colnames = c("Customer", "Sales Rep.", "District", "Type", "First Order", "Sales Amount"),
) |>
  formatCurrency(
    columns = 6,
    digits = 0,
    interval = 3,
    mark = " ",
    currency = " €",
    before = FALSE
  ) |>
  formatStyle(columns = c(1:6), fontSize = "12px")

# https://stackoverflow.com/questions/39775563/why-is-the-vertical-scroll-here-not-working
```
